### ISSUE TITLE
add_to_log function is deprecated in Moodle 2.7

### ISSUE THREAD

**Issue by techxplorer** [equella/moodle-mod_equella#33]
Hi,

I'm currently trying to integrate your module with Moodle 2.7. As part of a client upgrade project here at NetSpot. 

I note that there are 10 calls to the add_to_log function. This function has been deprecated in Moodle 2.7. As such it results in debugging being displayed to the user. More information is available here:

https://docs.moodle.org/dev/Migrating_logging_calls_in_plugins

Could you update the module to not use add_to_log in Moodle 2.7?

With thanks. 

-Corey

**Comment by dcai** [comment]
Closing
