### ISSUE TITLE
Equella module will not install on Moodle 3.0 sites

### ISSUE THREAD

**Issue by ttsilva90** [equella/moodle-mod_equella#37]
The Equella module will not install on a Moodle 3.0 site. Attempting to do so triggers the following fatal error:

Plugin mod_equella does not declare valid $plugin->component in its version.php.
Debug info: Unsupported $module syntax detected in version.php
Error code: detectedbrokenplugin

**Comment by dcai** [comment]
Hi @ttsilva90 I updated version.php in "dev" branch, it will be merged to master when moodle 3.0 releasees.
